import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Footer from "@/components/layout/Footer/Footer";
import Header from "@/components/layout/Header/Header";
import NavMobile from "@/components/layout/NavMobile/NavMobile";
import "./globals.css";
import { BackToTopButton } from "@/components/modules/BackToTopButton/BackToTopButton";
import ToastProvider from "@/components/modules/providers/ToastProvider";
import { CartProvider } from "@/src/context/CartContext";
import AuthInitializer from "@/components/modules/AuthInitializer/AuthInitializer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="FA_IR"
      dir="rtl"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="relative bg-custom-light dark:bg-[#0d1117] text-gray-900 dark:text-gray-100 transition-colors duration-300">
        <CartProvider>
          <AuthInitializer />
          <Header />
          {children}
          <Footer />
          <NavMobile />
          <BackToTopButton />
          <ToastProvider />
        </CartProvider>
      </body>
    </html>
  );
}
