// lib/mock-data.ts
import { Product } from "@/types/product";

const now = new Date();
const hoursFromNow = (h: number) =>
  new Date(now.getTime() + h * 60 * 60 * 1000);


export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-001",
    name: "فرمان اسپرت کربن‌فایبر Nardi Deep Corn",
    brand: "Nardi",
    category: "steering",
    description:
      "فرمان دست‌دوز ایتالیایی با رویه چرم ناپا و هسته کربن‌فایبر واقعی",
    image: "/images/product-car/02.jpg",
    originalPrice: 8_500_000,
    discountedPrice: 5_950_000,
    discountPercent: 30,
    review: { rating: 4.8, count: 214 },
    badges: ["exclusive", "limited_stock", "send_today"],
    specialSale: false,

    stockCount: 7,
    dealEndsAt: hoursFromNow(5),
    isFeatured: true,
    sku: "NRD-DC-001",
  },
  {
    id: "prod-002",
    name: "روکش صندلی چرم طبیعی Mercedes AMG",
    brand: "AutoLux",
    category: "seats",
    description:
      "روکش چرم طبیعی نانو با دوخت برجسته و لوگوی AMG، مناسب تمام مدل‌های مرسدس",
    image: "/images/product-car/03.jpg",
    originalPrice: 12_000_000,
    discountedPrice: 7_800_000,
    discountPercent: 35,
    review: { rating: 4.7, count: 189 },
    badges: ["bestseller", "special_sale"],
    specialSale: true,
    stockCount: 15,
    dealEndsAt: hoursFromNow(8),
    sku: "ALX-AMG-002",
  },
  {
    id: "prod-003",
    name: "سیستم صوتی JBL Club 9800 Harman",
    brand: "JBL",
    category: "audio",
    description:
      "کامل‌ترین سیستم صوتی خودرو با ۹ اسپیکر و ساب‌ووفر ۱۲ اینچی اکتیو",
    image: "/images/product-car/04.webp",
    originalPrice: 22_000_000,
    discountedPrice: 14_300_000,
    discountPercent: 35,
    review: { rating: 4.9, count: 321 },
    badges: ["limited_stock", "bestseller"],
    specialSale: false,
    stockCount: 4,
    dealEndsAt: hoursFromNow(3),
    isFeatured: true,
    sku: "JBL-9800-003",
  },
  {
    id: "prod-004",
    name: "نورپردازی محیطی RGB داخل خودرو ProLight",
    brand: "ProLight",
    category: "lighting",
    description: "سیستم نورپردازی هوشمند ۶۴ رنگ با اپ موبایل و سنسور موسیقی",
    image: "/images/product-car/01.jpg",
    originalPrice: 3_200_000,
    discountedPrice: 1_920_000,
    discountPercent: 40,
    review: { rating: 4.5, count: 567 },
    badges: ["send_today", "special_sale", "new"],
    specialSale: true,
    stockCount: 42,
    dealEndsAt: hoursFromNow(12),
    sku: "PRL-RGB-004",
  },
  {
    id: "prod-005",
    name: "خوشبوکننده لوکس Creed Aventus Car Edition",
    brand: "Creed",
    category: "fragrance",
    description:
      "عطر خودرو از برند فرانسوی کرید، ماندگاری ۶۰ روزه، اتاچ‌مان دریچه هوا",
    image: "/images/product-car/05.jpg",
    originalPrice: 1_800_000,
    discountedPrice: 1_260_000,
    discountPercent: 30,
    review: { rating: 4.6, count: 843 },
    badges: ["send_today", "bestseller"],
    specialSale: false,
    stockCount: 28,
    dealEndsAt: hoursFromNow(6),
    sku: "CRD-AVN-005",
  },
  {
    id: "prod-006",
    name: "کفپوش سه‌بعدی کربن‌لوک BMW سری ۵",
    brand: "3D Mats",
    category: "floor_mats",
    description:
      "کفپوش قالب‌گیری شده با تکنولوژی ۳D Scan اختصاصی BMW 5 Series 2020-2024",
    image: "/images/product-car/06.webp",
    originalPrice: 4_500_000,
    discountedPrice: 2_925_000,
    discountPercent: 35,
    review: { rating: 4.7, count: 156 },
    badges: ["exclusive", "limited_stock"],
    specialSale: false,
    stockCount: 9,
    dealEndsAt: hoursFromNow(9),
    sku: "3DM-BMW-006",
  },
  {
    id: "prod-007",
    name: "پدال آلومینیومی Racing Sport برای پورشه",
    brand: "TechArt",
    category: "steering",
    description:
      "مجموعه پدال آلومینیوم CNC با پوشش آنتی‌اسکید، سازگار با پورشه ۹۱۱ و کاین",
    image: "/images/product-car/07.jpg",
    originalPrice: 6_200_000,
    discountedPrice: 3_720_000,
    discountPercent: 40,
    review: { rating: 4.8, count: 98 },
    badges: ["exclusive", "new", "limited_stock"],
    specialSale: false,
    stockCount: 5,
    dealEndsAt: hoursFromNow(4),
    sku: "TCH-POR-007",
  },
  {
    id: "prod-008",
    name: "دوربین ۳۶۰ درجه داشبورد Garmin Dash Cam",
    brand: "Garmin",
    category: "accessories",
    description: "دوربین ضبط ۴K با دید شبانه، GPS داخلی و ۱۲۸GB حافظه داخلی",
    image: "/images/product-car/08.jpg",
    originalPrice: 9_800_000,
    discountedPrice: 6_860_000,
    discountPercent: 30,
    review: { rating: 4.9, count: 445 },
    badges: ["send_today", "bestseller", "special_sale"],
    specialSale: false,
    stockCount: 22,
    dealEndsAt: hoursFromNow(7),
    sku: "GRM-DCM-008",
  },
  {
    id: "prod-009",
    name: "هدرست لوکس Recaro Performance",
    brand: "Recaro",
    category: "seats",
    description:
      "هدرست تنظیم‌پذیر چرم آلکانتارا با مموری فوم ۴ لایه و لوگو سوزن‌دوزی",
    image: "/images/product-car/09.jpg",
    originalPrice: 5_400_000,
    discountedPrice: 3_780_000,
    discountPercent: 30,
    review: { rating: 4.6, count: 201 },
    badges: ["new", "send_today"],
    specialSale: false,
    stockCount: 18,
    dealEndsAt: hoursFromNow(11),
    sku: "RCR-PRM-009",
  },
  {
    id: "prod-010",
    name: "اکولایزر گرافیکی Pioneer DEQ-S1000A",
    brand: "Pioneer",
    category: "audio",
    description:
      "پردازشگر صدای ۱۳ باندی با تنظیم خودکار محیط اتاق و اتصال بلوتوث",
    image: "/images/product-car/10.jpg",
    originalPrice: 7_600_000,
    discountedPrice: 4_940_000,
    discountPercent: 35,
    review: { rating: 4.7, count: 134 },
    badges: ["limited_stock", "special_sale"],
    specialSale: true,
    stockCount: 6,
    dealEndsAt: hoursFromNow(5),
    sku: "PNR-DEQ-010",
  },
];

export const formatPrice = (price: number): string => {
  return new Intl.NumberFormat("fa-IR").format(price);
};
