// app/landing/components/ProductSlider.tsx

"use client";

import SliderProduct from "@/components/modules/SliderProduct/SliderProduct";

const products = [
  {
    id: "1",
    title: "تبلت سامسونگ مدل Galaxy Tab S8 Ultra",
    image: "/images/product/laptop-2.png",
    imageSlider: [
      { id: 1, imgSrc: "/images/product/laptop-1.png" },
      { id: 2, imgSrc: "/images/product/laptop-2.png" },
      { id: 3, imgSrc: "/images/product/laptop-3.png" },
      { id: 4, imgSrc: "/images/product/laptop-4.png" },
      { id: 5, imgSrc: "/images/product/laptop-5.png" },
      { id: 6, imgSrc: "/images/product/laptop-6.png" },
    ],
    count: 1,
    brandId: 1,
    discount: "3",
    price: 13550000,
    oldPrice: 13900000,
    rating: 4,
    offer: true,
    countdownToISO: "2028-01-01T15:30:00.000Z",
    colors: [
      { id: 1, code: "#0000ff", title: "آبی" },
      { id: 2, code: "#ff0000", title: "قرمز" },
    ],
    href: "/product",
  },
  {
    id: "2",
    title: "لپ‌تاپ ایسوس Zenbook 14",
    image: "/images/product/laptop-1.png",
    imageSlider: [
      { id: 1, imgSrc: "/images/product/laptop-1.png" },
      { id: 2, imgSrc: "/images/product/laptop-2.png" },
      { id: 3, imgSrc: "/images/product/laptop-3.png" },
      { id: 4, imgSrc: "/images/product/laptop-4.png" },
      { id: 5, imgSrc: "/images/product/laptop-5.png" },
      { id: 6, imgSrc: "/images/product/laptop-6.png" },
    ],
    count: 2,
    brandId: 1,
    discount: "5",
    price: 45000000,
    oldPrice: 47500000,
    offer: false,
    countdownToISO: "0",
    rating: 5,
    colors: [
      { id: 1, code: "#19df0f", title: "سبز" },
      { id: 2, code: "#dfd10f", title: "زرد" },
    ],
    href: "/product",
  },
  {
    id: "3",
    title: "تبلت سامسونگ مدل Galaxy Tab S8 Ultra ظرفیت 128 گیگابایت",
    image: "/images/product/laptop-3.png",
    imageSlider: [
      { id: 1, imgSrc: "/images/product/laptop-1.png" },
      { id: 2, imgSrc: "/images/product/laptop-2.png" },
      { id: 3, imgSrc: "/images/product/laptop-3.png" },
      { id: 4, imgSrc: "/images/product/laptop-4.png" },
      { id: 5, imgSrc: "/images/product/laptop-5.png" },
      { id: 6, imgSrc: "/images/product/laptop-6.png" },
    ],
    count: 0,
    discount: "3",
    brandId: 2,
    price: 13550000,
    oldPrice: 13900000,
    offer: true,
    countdownToISO: "2028-01-01T15:30:00.000Z",
    rating: 4,
    colors: [
      { id: 1, code: "#19df0f", title: "سبز" },
      { id: 2, code: ["#0000ff", "#ff0000"], title: "آبی-قرمز" },
    ],
    href: "/product",
  },
  {
    id: "4",
    title: "تبلت سامسونگ مدل S8",
    image: "/images/product/television-2.png",
    imageSlider: [
      { id: 1, imgSrc: "/images/product/laptop-1.png" },
      { id: 2, imgSrc: "/images/product/laptop-2.png" },
      { id: 3, imgSrc: "/images/product/laptop-3.png" },
      { id: 4, imgSrc: "/images/product/laptop-4.png" },
      { id: 5, imgSrc: "/images/product/laptop-5.png" },
      { id: 6, imgSrc: "/images/product/laptop-6.png" },
    ],
    count: 0,
    brandId: 2,
    discount: "3",
    price: 13550000,
    oldPrice: 13900000,
    rating: 4,
    offer: true,
    countdownToISO: "2028-01-01T15:30:00.000Z",
    colors: [
      { id: 1, code: "#19df0f", title: "سبز" },
      { id: 2, code: "#dfd10f", title: "زرد" },
    ],
    href: "/product",
  },
  {
    id: "5",
    title: "سامسونگ مدل S8",
    image: "/images/product/laptop-5.png",
    imageSlider: [
      { id: 1, imgSrc: "/images/product/laptop-1.png" },
      { id: 2, imgSrc: "/images/product/laptop-2.png" },
      { id: 3, imgSrc: "/images/product/laptop-3.png" },
      { id: 4, imgSrc: "/images/product/laptop-4.png" },
      { id: 5, imgSrc: "/images/product/laptop-5.png" },
      { id: 6, imgSrc: "/images/product/laptop-6.png" },
    ],
    count: 0,
    discount: "3",
    brandId: 3,
    price: 13550000,
    oldPrice: 13900000,
    rating: 4,
    offer: true,
    countdownToISO: "2028-01-01T15:30:00.000Z",
    colors: [
      { id: 1, code: "#19df0f", title: "سبز" },
      { id: 2, code: "#dfd10f", title: "زرد" },
    ],
    href: "/product",
  },
  {
    id: "6",
    title: "تبلت سامسونگ مدل Galaxy Tab S8 Ultra",
    image: "/images/product/laptop-2.png",
    imageSlider: [
      { id: 1, imgSrc: "/images/product/laptop-1.png" },
      { id: 2, imgSrc: "/images/product/laptop-2.png" },
      { id: 3, imgSrc: "/images/product/laptop-3.png" },
      { id: 4, imgSrc: "/images/product/laptop-4.png" },
      { id: 5, imgSrc: "/images/product/laptop-5.png" },
      { id: 6, imgSrc: "/images/product/laptop-6.png" },
    ],
    count: 1,
    brandId: 1,
    discount: "3",
    price: 13550000,
    oldPrice: 13900000,
    rating: 4,
    offer: true,
    countdownToISO: "2028-01-01T15:30:00.000Z",
    colors: [
      { id: 1, code: "#0000ff", title: "آبی" },
      { id: 2, code: "#ff0000", title: "قرمز" },
    ],
    href: "/product",
  },
  {
    id: "7",
    title: "لپ‌تاپ ایسوس Zenbook 14",
    image: "/images/product/laptop-1.png",
    imageSlider: [
      { id: 1, imgSrc: "/images/product/laptop-1.png" },
      { id: 2, imgSrc: "/images/product/laptop-2.png" },
      { id: 3, imgSrc: "/images/product/laptop-3.png" },
      { id: 4, imgSrc: "/images/product/laptop-4.png" },
      { id: 5, imgSrc: "/images/product/laptop-5.png" },
      { id: 6, imgSrc: "/images/product/laptop-6.png" },
    ],
    count: 2,
    brandId: 1,
    discount: "5",
    price: 45000000,
    oldPrice: 47500000,
    offer: false,
    countdownToISO: "0",
    rating: 5,
    colors: [
      { id: 1, code: "#19df0f", title: "سبز" },
      { id: 2, code: "#dfd10f", title: "زرد" },
    ],
    href: "/product",
  },
  {
    id: "8",
    title: "تبلت سامسونگ مدل Galaxy Tab S8 Ultra ظرفیت 128 گیگابایت",
    image: "/images/product/laptop-3.png",
    imageSlider: [
      { id: 1, imgSrc: "/images/product/laptop-1.png" },
      { id: 2, imgSrc: "/images/product/laptop-2.png" },
      { id: 3, imgSrc: "/images/product/laptop-3.png" },
      { id: 4, imgSrc: "/images/product/laptop-4.png" },
      { id: 5, imgSrc: "/images/product/laptop-5.png" },
      { id: 6, imgSrc: "/images/product/laptop-6.png" },
    ],
    count: 0,
    discount: "3",
    brandId: 2,
    price: 13550000,
    oldPrice: 13900000,
    offer: true,
    countdownToISO: "2028-01-01T15:30:00.000Z",
    rating: 4,
    colors: [
      { id: 1, code: "#19df0f", title: "سبز" },
      { id: 2, code: ["#0000ff", "#ff0000"], title: "آبی-قرمز" },
    ],
    href: "/product",
  },
  {
    id: "9",
    title: "تبلت سامسونگ مدل S8",
    image: "/images/product/television-2.png",
    imageSlider: [
      { id: 1, imgSrc: "/images/product/laptop-1.png" },
      { id: 2, imgSrc: "/images/product/laptop-2.png" },
      { id: 3, imgSrc: "/images/product/laptop-3.png" },
      { id: 4, imgSrc: "/images/product/laptop-4.png" },
      { id: 5, imgSrc: "/images/product/laptop-5.png" },
      { id: 6, imgSrc: "/images/product/laptop-6.png" },
    ],
    count: 0,
    brandId: 2,
    discount: "3",
    price: 13550000,
    oldPrice: 13900000,
    rating: 4,
    offer: true,
    countdownToISO: "2028-01-01T15:30:00.000Z",
    colors: [
      { id: 1, code: "#19df0f", title: "سبز" },
      { id: 2, code: "#dfd10f", title: "زرد" },
    ],
    href: "/product",
  },
  {
    id: "10",
    title: "سامسونگ مدل S8",
    image: "/images/product/laptop-5.png",
    imageSlider: [
      { id: 1, imgSrc: "/images/product/laptop-1.png" },
      { id: 2, imgSrc: "/images/product/laptop-2.png" },
      { id: 3, imgSrc: "/images/product/laptop-3.png" },
      { id: 4, imgSrc: "/images/product/laptop-4.png" },
      { id: 5, imgSrc: "/images/product/laptop-5.png" },
      { id: 6, imgSrc: "/images/product/laptop-6.png" },
    ],
    count: 0,
    discount: "3",
    brandId: 3,
    price: 13550000,
    oldPrice: 13900000,
    rating: 4,
    offer: true,
    countdownToISO: "2028-01-01T15:30:00.000Z",
    colors: [
      { id: 1, code: "#19df0f", title: "سبز" },
      { id: 2, code: "#dfd10f", title: "زرد" },
    ],
    href: "/product",
  },
];

export default function ProductSlider() {
  return (
    <section className="mx-2 my-4">
      <SliderProduct
        title="محصولات پیشنهادی"
        products={products}
        loop={false}
        href={""}
      />
    </section>
  );
}
